export const rooms = [
  {
    _id: "66957866c103d072cc2b4aae",
    roomName: "watch anime",
    isPrivate: false,
    isLive: true,
    permissions: {
      chat: false,
      videoCall: true,
      audioCall: false,
      playList: true,
      player: false,
    },
    description: "This room is for watching anime",
    createdAt: "2024-07-15T19:28:38.797Z",
    updatedAt: "2024-07-16T14:27:17.885Z",
    __v: 0,
    note: "keep ur behaviour good",
    isJoined: true,
    isAdmin: true,
    isCreatedByUser: true,
  },
  {
    _id: "66957866c103d072cc2b4aab",
    roomName: "gaming hub",
    isPrivate: true,
    isLive: false,
    permissions: {
      chat: true,
      videoCall: true,
      audioCall: true,
      playList: false,
      player: true,
    },
    description: "A private room for gaming enthusiasts.",
    createdAt: "2024-07-16T10:20:38.797Z",
    updatedAt: "2024-07-17T12:27:17.885Z",
    __v: 0,
    note: "Enjoy your games!",
    isJoined: false,
    isAdmin: false,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4aac",
    roomName: "book club",
    isPrivate: false,
    isLive: false,
    permissions: {
      chat: true,
      videoCall: false,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Discuss your favorite books here.",
    createdAt: "2024-07-17T11:28:38.797Z",
    updatedAt: "2024-07-18T15:27:17.885Z",
    __v: 0,
    note: "Be respectful to others' opinions.",
    isJoined: true,
    isAdmin: false,
    isCreatedByUser: true,
  },
  {
    _id: "66957866c103d072cc2b4aad",
    roomName: "movie night",
    isPrivate: false,
    isLive: true,
    permissions: {
      chat: true,
      videoCall: false,
      audioCall: false,
      playList: true,
      player: true,
    },
    description: "Watch movies together with friends.",
    createdAt: "2024-07-18T14:30:38.797Z",
    updatedAt: "2024-07-19T16:27:17.885Z",
    __v: 0,
    note: "Have fun!",
    isJoined: true,
    isAdmin: true,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4aae",
    roomName: "fitness group",
    isPrivate: false,
    isLive: true,
    permissions: {
      chat: true,
      videoCall: true,
      audioCall: true,
      playList: false,
      player: false,
    },
    description: "Join this room for fitness tips and workouts.",
    createdAt: "2024-07-19T16:28:38.797Z",
    updatedAt: "2024-07-20T18:27:17.885Z",
    __v: 0,
    note: "Stay healthy and motivated!",
    isJoined: false,
    isAdmin: false,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4aaf",
    roomName: "music lovers",
    isPrivate: true,
    isLive: false,
    permissions: {
      chat: true,
      videoCall: false,
      audioCall: true,
      playList: true,
      player: true,
    },
    description: "Share and discuss your favorite music.",
    createdAt: "2024-07-20T11:28:38.797Z",
    updatedAt: "2024-07-21T13:27:17.885Z",
    __v: 0,
    note: "Respect copyright laws.",
    isJoined: true,
    isAdmin: true,
    isCreatedByUser: true,
  },
  {
    _id: "66957866c103d072cc2b4ab0",
    roomName: "tech talk",
    isPrivate: false,
    isLive: false,
    permissions: {
      chat: true,
      videoCall: true,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Discuss the latest in technology.",
    createdAt: "2024-07-21T12:30:38.797Z",
    updatedAt: "2024-07-22T14:27:17.885Z",
    __v: 0,
    note: "Stay updated with tech trends.",
    isJoined: false,
    isAdmin: false,
    isCreatedByUser: true,
  },
  {
    _id: "66957866c103d072cc2b4ab1",
    roomName: "art gallery",
    isPrivate: true,
    isLive: false,
    permissions: {
      chat: true,
      videoCall: false,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Share and discuss artworks.",
    createdAt: "2024-07-22T10:28:38.797Z",
    updatedAt: "2024-07-23T12:27:17.885Z",
    __v: 0,
    note: "Be kind and constructive.",
    isJoined: true,
    isAdmin: false,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4ab2",
    roomName: "coding dojo",
    isPrivate: false,
    isLive: true,
    permissions: {
      chat: true,
      videoCall: true,
      audioCall: true,
      playList: false,
      player: false,
    },
    description: "Collaborate and learn coding skills.",
    createdAt: "2024-07-23T09:28:38.797Z",
    updatedAt: "2024-07-24T11:27:17.885Z",
    __v: 0,
    note: "Share knowledge and code.",
    isJoined: false,
    isAdmin: true,
    isCreatedByUser: true,
  },
  {
    _id: "66957866c103d072cc2b4ab3",
    roomName: "cooking class",
    isPrivate: true,
    isLive: false,
    permissions: {
      chat: true,
      videoCall: false,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Learn and share cooking recipes.",
    createdAt: "2024-07-24T08:28:38.797Z",
    updatedAt: "2024-07-25T10:27:17.885Z",
    __v: 0,
    note: "Cook and share delicious recipes.",
    isJoined: true,
    isAdmin: false,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4ab4",
    roomName: "travel diaries",
    isPrivate: false,
    isLive: true,
    permissions: {
      chat: true,
      videoCall: true,
      audioCall: true,
      playList: false,
      player: false,
    },
    description: "Share your travel experiences and tips.",
    createdAt: "2024-07-25T07:28:38.797Z",
    updatedAt: "2024-07-26T09:27:17.885Z",
    __v: 0,
    note: "Share your journeys and adventures.",
    isJoined: false,
    isAdmin: false,
    isCreatedByUser: true,
  },
  {
    _id: "66957866c103d072cc2b4ab5",
    roomName: "sports zone",
    isPrivate: false,
    isLive: false,
    permissions: {
      chat: true,
      videoCall: false,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Discuss sports news and events.",
    createdAt: "2024-07-26T06:28:38.797Z",
    updatedAt: "2024-07-27T08:27:17.885Z",
    __v: 0,
    note: "Stay updated with sports.",
    isJoined: true,
    isAdmin: true,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4ab6",
    roomName: "fashion trends",
    isPrivate: true,
    isLive: true,
    permissions: {
      chat: true,
      videoCall: true,
      audioCall: true,
      playList: false,
      player: false,
    },
    description: "Discuss the latest in fashion.",
    createdAt: "2024-07-27T05:28:38.797Z",
    updatedAt: "2024-07-28T07:27:17.885Z",
    __v: 0,
    note: "Stay stylish!",
    isJoined: false,
    isAdmin: true,
    isCreatedByUser: true,
  },
  {
    _id: "66957866c103d072cc2b4ab7",
    roomName: "history buffs",
    isPrivate: false,
    isLive: false,
    permissions: {
      chat: true,
      videoCall: false,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Discuss historical events and figures.",
    createdAt: "2024-07-28T04:28:38.797Z",
    updatedAt: "2024-07-29T06:27:17.885Z",
    __v: 0,
    note: "Share historical knowledge.",
    isJoined: true,
    isAdmin: false,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4ab8",
    roomName: "writing workshop",
    isPrivate: true,
    isLive: false,
    permissions: {
      chat: true,
      videoCall: false,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Improve your writing skills together.",
    createdAt: "2024-07-29T03:28:38.797Z",
    updatedAt: "2024-07-30T05:27:17.885Z",
    __v: 0,
    note: "Write and critique each other's work.",
    isJoined: false,
    isAdmin: false,
    isCreatedByUser: true,
  },
  {
    _id: "66957866c103d072cc2b4ab9",
    roomName: "science club",
    isPrivate: false,
    isLive: true,
    permissions: {
      chat: true,
      videoCall: true,
      audioCall: true,
      playList: false,
      player: false,
    },
    description: "Discuss scientific discoveries and theories.",
    createdAt: "2024-07-30T02:28:38.797Z",
    updatedAt: "2024-07-31T04:27:17.885Z",
    __v: 0,
    note: "Stay curious and informed.",
    isJoined: true,
    isAdmin: true,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4aba",
    roomName: "photography enthusiasts",
    isPrivate: true,
    isLive: false,
    permissions: {
      chat: true,
      videoCall: false,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Share and critique photography.",
    createdAt: "2024-07-31T01:28:38.797Z",
    updatedAt: "2024-08-01T03:27:17.885Z",
    __v: 0,
    note: "Respect all photographers.",
    isJoined: false,
    isAdmin: true,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4abb",
    roomName: "environmental activism",
    isPrivate: false,
    isLive: true,
    permissions: {
      chat: true,
      videoCall: true,
      audioCall: true,
      playList: false,
      player: false,
    },
    description: "Discuss environmental issues and solutions.",
    createdAt: "2024-08-01T00:28:38.797Z",
    updatedAt: "2024-08-02T02:27:17.885Z",
    __v: 0,
    note: "Protect our planet.",
    isJoined: true,
    isAdmin: false,
    isCreatedByUser: true,
  },
  {
    _id: "66957866c103d072cc2b4abc",
    roomName: "language exchange",
    isPrivate: true,
    isLive: false,
    permissions: {
      chat: true,
      videoCall: false,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Practice and learn new languages.",
    createdAt: "2024-08-02T11:28:38.797Z",
    updatedAt: "2024-08-03T13:27:17.885Z",
    __v: 0,
    note: "Enhance your language skills.",
    isJoined: true,
    isAdmin: false,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4abd",
    roomName: "DIY projects",
    isPrivate: false,
    isLive: true,
    permissions: {
      chat: true,
      videoCall: true,
      audioCall: true,
      playList: false,
      player: false,
    },
    description: "Share and get ideas for DIY projects.",
    createdAt: "2024-08-03T10:28:38.797Z",
    updatedAt: "2024-08-04T12:27:17.885Z",
    __v: 0,
    note: "Create and innovate.",
    isJoined: false,
    isAdmin: true,
    isCreatedByUser: true,
  },
  {
    _id: "66957866c103d072cc2b4abe",
    roomName: "startups",
    isPrivate: false,
    isLive: false,
    permissions: {
      chat: true,
      videoCall: true,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Discuss and collaborate on startups.",
    createdAt: "2024-08-04T09:28:38.797Z",
    updatedAt: "2024-08-05T11:27:17.885Z",
    __v: 0,
    note: "Support and grow new ideas.",
    isJoined: true,
    isAdmin: false,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4abf",
    roomName: "parenting tips",
    isPrivate: true,
    isLive: true,
    permissions: {
      chat: true,
      videoCall: false,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Share parenting tips and advice.",
    createdAt: "2024-08-05T08:28:38.797Z",
    updatedAt: "2024-08-06T10:27:17.885Z",
    __v: 0,
    note: "Help and support each other.",
    isJoined: false,
    isAdmin: true,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4ac0",
    roomName: "philosophy discussions",
    isPrivate: false,
    isLive: false,
    permissions: {
      chat: true,
      videoCall: false,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Engage in deep philosophical discussions.",
    createdAt: "2024-08-06T07:28:38.797Z",
    updatedAt: "2024-08-07T09:27:17.885Z",
    __v: 0,
    note: "Explore profound ideas.",
    isJoined: true,
    isAdmin: false,
    isCreatedByUser: true,
  },
  {
    _id: "66957866c103d072cc2b4ac1",
    roomName: "health and wellness",
    isPrivate: true,
    isLive: true,
    permissions: {
      chat: true,
      videoCall: true,
      audioCall: true,
      playList: false,
      player: false,
    },
    description: "Discuss health and wellness topics.",
    createdAt: "2024-08-07T06:28:38.797Z",
    updatedAt: "2024-08-08T08:27:17.885Z",
    __v: 0,
    note: "Promote healthy lifestyles.",
    isJoined: false,
    isAdmin: true,
    isCreatedByUser: true,
  },
  {
    _id: "66957866c103d072cc2b4ac2",
    roomName: "gaming strategies",
    isPrivate: false,
    isLive: true,
    permissions: {
      chat: true,
      videoCall: false,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Discuss and share gaming strategies.",
    createdAt: "2024-08-08T05:28:38.797Z",
    updatedAt: "2024-08-09T07:27:17.885Z",
    __v: 0,
    note: "Improve your gameplay.",
    isJoined: true,
    isAdmin: false,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4ac3",
    roomName: "travel photography",
    isPrivate: true,
    isLive: false,
    permissions: {
      chat: true,
      videoCall: false,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Share and critique travel photography.",
    createdAt: "2024-08-09T04:28:38.797Z",
    updatedAt: "2024-08-10T06:27:17.885Z",
    __v: 0,
    note: "Capture and share your travels.",
    isJoined: false,
    isAdmin: true,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4ac4",
    roomName: "book reviews",
    isPrivate: false,
    isLive: true,
    permissions: {
      chat: true,
      videoCall: true,
      audioCall: true,
      playList: false,
      player: false,
    },
    description: "Review and discuss books.",
    createdAt: "2024-08-10T03:28:38.797Z",
    updatedAt: "2024-08-11T05:27:17.885Z",
    __v: 0,
    note: "Share your thoughts on books.",
    isJoined: true,
    isAdmin: true,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4ac5",
    roomName: "spirituality",
    isPrivate: true,
    isLive: true,
    permissions: {
      chat: true,
      videoCall: false,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Discuss spiritual topics and practices.",
    createdAt: "2024-08-11T02:28:38.797Z",
    updatedAt: "2024-08-12T04:27:17.885Z",
    __v: 0,
    note: "Explore your inner self.",
    isJoined: false,
    isAdmin: true,
    isCreatedByUser: true,
  },
  {
    _id: "66957866c103d072cc2b4ac6",
    roomName: "education",
    isPrivate: false,
    isLive: false,
    permissions: {
      chat: true,
      videoCall: true,
      audioCall: false,
      playList: false,
      player: false,
    },
    description: "Discuss and share educational resources.",
    createdAt: "2024-08-12T01:28:38.797Z",
    updatedAt: "2024-08-13T03:27:17.885Z",
    __v: 0,
    note: "Enhance your knowledge.",
    isJoined: true,
    isAdmin: false,
    isCreatedByUser: false,
  },
  {
    _id: "66957866c103d072cc2b4ac7",
    roomName: "startup ideas",
    isPrivate: true,
    isLive: true,
    permissions: {
      chat: true,
      videoCall: true,
      audioCall: true,
      playList: false,
      player: false,
    },
    description: "Brainstorm and discuss startup ideas.",
    createdAt: "2024-08-13T00:28:38.797Z",
    updatedAt: "2024-08-14T02:27:17.885Z",
    __v: 0,
    note: "Cultivate innovative ideas.",
    isJoined: false,
    isAdmin: true,
    isCreatedByUser: false,
  },
];
